env:
   global:
     - CONAN_REFERENCE: "pybind11/2.3.0"
     - CONAN_USERNAME: "conan"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_CHANNEL: "stable"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "2.7"
   services:
     - docker

matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh